% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Feb-2024 11:47:28
%  MATLAB version: 23.2.0.2428915 (R2023b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('consensus_multilayer.mat');

A_g1 = saveVarsMat.A_g1; % <76x1 cell> too many elements at A_g1{1,1}

A_g2 = saveVarsMat.A_g2; % <61x1 cell> too many elements at A_g2{1,1}

B_g1 = saveVarsMat.B_g1; % <15200x15200 double> too many elements

B_g2 = saveVarsMat.B_g2; % <12200x12200 double> too many elements

C_g1 = [1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 2; 2; 2; 2; 2; 2; 2; ...
        2; 2; 2; 2; 2; 2; 2; 2; 2; 3; 4; 4; 2; 2; 4; 4; 4; 6; 2; 4; 4; ...
        4; 2; 2; 4; 2; 4; 2; 4; 5; 2; 6; 2; 5; 5; 5; 5; 5; 5; 4; 4; 4; ...
        4; 5; 5; 5; 4; 4; 5; 5; 5; 4; 5; 5; 5; 5; 5; 5; 4; 5; 5; 5; 5; ...
        5; 5; 5; 5; 5; 5; 5; 5; 5; 5; 5; 1; 5; 5; 5; 1; 1; 1; 1; 1; 1; ...
        1; 1; 1; 1; 1; 1; 1; 1; 1; 4; 2; 2; 2; 2; 2; 2; 2; 2; 2; 2; 2; ...
        2; 2; 2; 2; 2; 2; 2; 2; 1; 3; 2; 4; 2; 4; 4; 4; 6; 2; 7; 4; 4; ...
        5; 3; 2; 7; 2; 2; 4; 2; 2; 2; 2; 5; 5; 5; 5; 5; 1; 4; 4; 4; 4; ...
        5; 5; 5; 4; 4; 5; 4; 5; 1; 5; 4; 5; 5; 5; 5; 5; 5; 5; 5; 5; 5; ...
        5; 5; 5; 5; 5; 5; 5; 5; 1; 5; 5];

C_g2 = [1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 3; 3; 3; 3; 3; 3; 4; ...
        5; 6; 6; 6; 6; 6; 6; 6; 6; 7; 2; 2; 6; 6; 2; 2; 2; 2; 6; 2; 2; ...
        2; 3; 3; 2; 3; 3; 3; 3; 8; 5; 5; 4; 7; 7; 7; 7; 7; 9; 8; 2; 2; ...
        8; 8; 8; 8; 2; 8; 2; 8; 8; 5; 7; 7; 9; 8; 9; 8; 8; 8; 8; 8; 8; ...
        8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 1; 8; 8; 8; 7; 7; 1; 1; 1; 1; ...
        1; 1; 1; 1; 1; 1; 1; 1; 1; 1; 3; 3; 3; 3; 3; 3; 3; 3; 6; 6; 6; ...
        6; 6; 6; 6; 6; 6; 6; 6; 7; 9; 3; 2; 6; 2; 2; 2; 2; 6; 6; 2; 2; ...
        9; 3; 3; 4; 3; 3; 3; 3; 5; 5; 4; 7; 7; 8; 7; 7; 7; 2; 2; 2; 7; ...
        8; 8; 8; 2; 2; 2; 2; 8; 1; 8; 5; 8; 8; 8; 8; 8; 7; 8; 9; 8; 9; ...
        8; 8; 8; 8; 8; 8; 8; 8; 1; 8; 8];

K_g1 = 14;

K_g2 = 12;

N = 200;

PP_g1 = saveVarsMat.PP_g1; % <1x1 function_handle> unsupported class

PP_g2 = saveVarsMat.PP_g2; % <1x1 function_handle> unsupported class

Q_g1 = single(0.241157964);

Q_g2 = single(0.172974348);

S_g1 = saveVarsMat.S_g1; % <200x76 double> too many elements

S_g2 = saveVarsMat.S_g2; % <200x61 double> too many elements

T_g1 = 76;

T_g2 = 61;

corr_g1 = saveVarsMat.corr_g1; % <200x200x76 single> too many elements

corr_g2 = saveVarsMat.corr_g2; % <200x200x61 single> too many elements

filename = 'S_sci_1.3,-1.0.mat';

gamma = 1.3;

log_omega = -1;

omega = 0.1;

twom_g1 = single(749720.5);

twom_g2 = single(648367.875);

clear saveVarsMat;
